import os
import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any
from xml.sax.saxutils import escape as xml_escape
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from app.core.config import settings

class ReportService:
    @staticmethod
    def generate_pdf_report(
        workspace_name: str,
        workspace_id: str,
        report_name: str,
        saved_insights: List[Dict[str, Any]],
        analyses: List[Dict[str, Any]],
        dataset_info: Dict[str, Any]
    ) -> str:
        """
        Generates a PDF report and saves it under backend/storage/reports/{workspace_id}/{report_id}.pdf
        Returns relative/absolute file path.
        """
        report_id = str(uuid.uuid4())
        workspace_dir = os.path.join(settings.REPORTS_DIR, workspace_id)
        os.makedirs(workspace_dir, exist_ok=True)
        file_path = os.path.join(workspace_dir, f"{report_id}.pdf")

        doc = SimpleDocTemplate(
            file_path,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )

        styles = getSampleStyleSheet()
        
        # Custom ReportLab Styles
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontSize=24,
            leading=28,
            textColor=colors.HexColor('#1e1b4b'),
            spaceAfter=10
        )
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#475569'),
            spaceAfter=20
        )
        heading_style = ParagraphStyle(
            'SectionHeading',
            parent=styles['Heading2'],
            fontSize=16,
            leading=20,
            textColor=colors.HexColor('#4f46e5'),
            spaceBefore=15,
            spaceAfter=10
        )
        body_style = ParagraphStyle(
            'ReportBody',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=8
        )
        bullet_style = ParagraphStyle(
            'ReportBullet',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#1e293b'),
            leftIndent=15,
            spaceAfter=4
        )

        elements = []

        # Title Header
        elements.append(Paragraph(f"Executive Analytics Report: {xml_escape(report_name)}", title_style))
        elements.append(Paragraph(f"Workspace: <b>{xml_escape(workspace_name)}</b> | Generated on: {datetime.now(timezone.utc).strftime('%B %d, %Y')}", subtitle_style))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366f1'), spaceAfter=15))

        # 1. Executive Summary
        elements.append(Paragraph("1. Executive Summary", heading_style))
        elements.append(Paragraph(
            "This report summarizes key data insights, quantitative trends, and analytical recommendations "
            "generated by Graph Analytics Multi-Agent Stateful Data Analysis Engine.", body_style
        ))

        # 2. Dataset Overview & Data Quality Health Score
        if dataset_info:
            elements.append(Paragraph("2. Dataset Profile & Data Quality", heading_style))
            filename = dataset_info.get("filename", "Uploaded Dataset")
            rows = dataset_info.get("row_count", 0)
            cols = dataset_info.get("column_count", 0)
            q_score = dataset_info.get("quality_score", 100.0)

            ds_table_data = [
                ["Dataset File", "Total Rows", "Total Columns", "Data Quality Score"],
                [str(filename), f"{rows:,}", str(cols), f"{q_score}%"]
            ]
            t = Table(ds_table_data, colWidths=[200, 100, 100, 120])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4f46e5')),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                ('BOTTOMPADDING', (0,0), (-1,0), 8),
                ('BACKGROUND', (0,1), (-1,-1), colors.HexColor('#f8fafc')),
                ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
            ]))
            elements.append(t)
            elements.append(Spacer(1, 15))

        # 3. Saved Insights & Major Business Findings
        elements.append(Paragraph("3. Major Business Insights", heading_style))
        if saved_insights:
            for idx, ins in enumerate(saved_insights, 1):
                content = ins.get("content", "")
                elements.append(Paragraph(f"• <b>Insight #{idx}:</b> {xml_escape(content)}", bullet_style))
        else:
            elements.append(Paragraph("No explicit saved insights attached to this report.", body_style))

        elements.append(Spacer(1, 10))

        # 4. Detailed Analyses Overview
        elements.append(Paragraph("4. Detailed Analytical Findings", heading_style))
        if analyses:
            for idx, a in enumerate(analyses, 1):
                q = a.get("question", "")
                res_sum = a.get("insights", "")
                q_escaped = xml_escape(q)
                elements.append(Paragraph(f"<b>Query #{idx}: {q_escaped}</b>", ParagraphStyle('QStyle', parent=body_style, fontName='Helvetica-Bold', textColor=colors.HexColor('#1e1b4b'))))
                if res_sum:
                    elements.append(Paragraph(f"{xml_escape(res_sum)}", body_style))
                elements.append(Spacer(1, 5))
        else:
            elements.append(Paragraph("No analysis history items attached.", body_style))

        # 5. Methodology & Disclaimer
        elements.append(Spacer(1, 15))
        elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceAfter=10))
        elements.append(Paragraph("<b>Methodology & Safety Note:</b> All computations were executed using deterministic Pandas logic in an isolated AST-validated sandbox. Numerical metrics are derived directly from the verified underlying data.", subtitle_style))

        doc.build(elements)
        return file_path

report_service = ReportService()
